export const GUILD_CREATE = 'GUILD_CREATE';
export const PRESENCE_UPDATE = 'PRESENCE_UPDATE';
export const MESSAGE_CREATE = 'MESSAGE_CREATE';
export const TYPING_START = 'TYPING_START';
export const MESSAGE_REACTION_ADD = 'MESSAGE_REACTION_ADD';
export const MESSAGE_REACTION_REMOVE = 'MESSAGE_REACTION_REMOVE';
